print("---------------------------------------------------------")
print("🔥 The Multi-Camera Tracking Pipeline has been upgraded! 🔥")
print("---------------------------------------------------------")
print("To view the new Web Dashboard, run the following command:\n")
print("    uv run streamlit run dashboard/app.py\n")
print("---------------------------------------------------------")